// Code generated by ent, DO NOT EDIT.

package gtk

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the gtk type in the database.
	Label = "gtk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldNik holds the string denoting the nik field in the database.
	FieldNik = "nik"
	// FieldNuptk holds the string denoting the nuptk field in the database.
	FieldNuptk = "nuptk"
	// FieldFullName holds the string denoting the full_name field in the database.
	FieldFullName = "full_name"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldBirthPlace holds the string denoting the birth_place field in the database.
	FieldBirthPlace = "birth_place"
	// FieldBirthDate holds the string denoting the birth_date field in the database.
	FieldBirthDate = "birth_date"
	// FieldEmploymentStatus holds the string denoting the employment_status field in the database.
	FieldEmploymentStatus = "employment_status"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePositions holds the string denoting the positions edge name in mutations.
	EdgePositions = "positions"
	// Table holds the table name of the gtk in the database.
	Table = "gtks"
	// PositionsTable is the table that holds the positions relation/edge.
	PositionsTable = "gtk_positions"
	// PositionsInverseTable is the table name for the GtkPosition entity.
	// It exists in this package in order to avoid circular dependency with the "gtkposition" package.
	PositionsInverseTable = "gtk_positions"
	// PositionsColumn is the table column denoting the positions relation/edge.
	PositionsColumn = "gtk_id"
)

// Columns holds all SQL columns for gtk fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldNik,
	FieldNuptk,
	FieldFullName,
	FieldGender,
	FieldBirthPlace,
	FieldBirthDate,
	FieldEmploymentStatus,
	FieldIsActive,
	FieldJoinedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NikValidator is a validator for the "nik" field. It is called by the builders before save.
	NikValidator func(string) error
	// NuptkValidator is a validator for the "nuptk" field. It is called by the builders before save.
	NuptkValidator func(string) error
	// FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	FullNameValidator func(string) error
	// GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	GenderValidator func(string) error
	// BirthPlaceValidator is a validator for the "birth_place" field. It is called by the builders before save.
	BirthPlaceValidator func(string) error
	// EmploymentStatusValidator is a validator for the "employment_status" field. It is called by the builders before save.
	EmploymentStatusValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Gtk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNik orders the results by the nik field.
func ByNik(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNik, opts...).ToFunc()
}

// ByNuptk orders the results by the nuptk field.
func ByNuptk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNuptk, opts...).ToFunc()
}

// ByFullName orders the results by the full_name field.
func ByFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullName, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByBirthPlace orders the results by the birth_place field.
func ByBirthPlace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBirthPlace, opts...).ToFunc()
}

// ByBirthDate orders the results by the birth_date field.
func ByBirthDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBirthDate, opts...).ToFunc()
}

// ByEmploymentStatus orders the results by the employment_status field.
func ByEmploymentStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmploymentStatus, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPositionsCount orders the results by positions count.
func ByPositionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPositionsStep(), opts...)
	}
}

// ByPositions orders the results by positions terms.
func ByPositions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPositionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPositionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PositionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PositionsTable, PositionsColumn),
	)
}
