// Code generated by ent, DO NOT EDIT.

package gtk

import (
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldUserID, v))
}

// Nik applies equality check predicate on the "nik" field. It's identical to NikEQ.
func Nik(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldNik, v))
}

// Nuptk applies equality check predicate on the "nuptk" field. It's identical to NuptkEQ.
func Nuptk(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldNuptk, v))
}

// FullName applies equality check predicate on the "full_name" field. It's identical to FullNameEQ.
func FullName(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldFullName, v))
}

// Gender applies equality check predicate on the "gender" field. It's identical to GenderEQ.
func Gender(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldGender, v))
}

// BirthPlace applies equality check predicate on the "birth_place" field. It's identical to BirthPlaceEQ.
func BirthPlace(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldBirthPlace, v))
}

// BirthDate applies equality check predicate on the "birth_date" field. It's identical to BirthDateEQ.
func BirthDate(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldBirthDate, v))
}

// EmploymentStatus applies equality check predicate on the "employment_status" field. It's identical to EmploymentStatusEQ.
func EmploymentStatus(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldEmploymentStatus, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldIsActive, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldJoinedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Gtk {
	return predicate.Gtk(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Gtk {
	return predicate.Gtk(sql.FieldNotNull(FieldUserID))
}

// NikEQ applies the EQ predicate on the "nik" field.
func NikEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldNik, v))
}

// NikNEQ applies the NEQ predicate on the "nik" field.
func NikNEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldNik, v))
}

// NikIn applies the In predicate on the "nik" field.
func NikIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldNik, vs...))
}

// NikNotIn applies the NotIn predicate on the "nik" field.
func NikNotIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldNik, vs...))
}

// NikGT applies the GT predicate on the "nik" field.
func NikGT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldNik, v))
}

// NikGTE applies the GTE predicate on the "nik" field.
func NikGTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldNik, v))
}

// NikLT applies the LT predicate on the "nik" field.
func NikLT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldNik, v))
}

// NikLTE applies the LTE predicate on the "nik" field.
func NikLTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldNik, v))
}

// NikContains applies the Contains predicate on the "nik" field.
func NikContains(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContains(FieldNik, v))
}

// NikHasPrefix applies the HasPrefix predicate on the "nik" field.
func NikHasPrefix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasPrefix(FieldNik, v))
}

// NikHasSuffix applies the HasSuffix predicate on the "nik" field.
func NikHasSuffix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasSuffix(FieldNik, v))
}

// NikEqualFold applies the EqualFold predicate on the "nik" field.
func NikEqualFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEqualFold(FieldNik, v))
}

// NikContainsFold applies the ContainsFold predicate on the "nik" field.
func NikContainsFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContainsFold(FieldNik, v))
}

// NuptkEQ applies the EQ predicate on the "nuptk" field.
func NuptkEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldNuptk, v))
}

// NuptkNEQ applies the NEQ predicate on the "nuptk" field.
func NuptkNEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldNuptk, v))
}

// NuptkIn applies the In predicate on the "nuptk" field.
func NuptkIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldNuptk, vs...))
}

// NuptkNotIn applies the NotIn predicate on the "nuptk" field.
func NuptkNotIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldNuptk, vs...))
}

// NuptkGT applies the GT predicate on the "nuptk" field.
func NuptkGT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldNuptk, v))
}

// NuptkGTE applies the GTE predicate on the "nuptk" field.
func NuptkGTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldNuptk, v))
}

// NuptkLT applies the LT predicate on the "nuptk" field.
func NuptkLT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldNuptk, v))
}

// NuptkLTE applies the LTE predicate on the "nuptk" field.
func NuptkLTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldNuptk, v))
}

// NuptkContains applies the Contains predicate on the "nuptk" field.
func NuptkContains(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContains(FieldNuptk, v))
}

// NuptkHasPrefix applies the HasPrefix predicate on the "nuptk" field.
func NuptkHasPrefix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasPrefix(FieldNuptk, v))
}

// NuptkHasSuffix applies the HasSuffix predicate on the "nuptk" field.
func NuptkHasSuffix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasSuffix(FieldNuptk, v))
}

// NuptkIsNil applies the IsNil predicate on the "nuptk" field.
func NuptkIsNil() predicate.Gtk {
	return predicate.Gtk(sql.FieldIsNull(FieldNuptk))
}

// NuptkNotNil applies the NotNil predicate on the "nuptk" field.
func NuptkNotNil() predicate.Gtk {
	return predicate.Gtk(sql.FieldNotNull(FieldNuptk))
}

// NuptkEqualFold applies the EqualFold predicate on the "nuptk" field.
func NuptkEqualFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEqualFold(FieldNuptk, v))
}

// NuptkContainsFold applies the ContainsFold predicate on the "nuptk" field.
func NuptkContainsFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContainsFold(FieldNuptk, v))
}

// FullNameEQ applies the EQ predicate on the "full_name" field.
func FullNameEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldFullName, v))
}

// FullNameNEQ applies the NEQ predicate on the "full_name" field.
func FullNameNEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldFullName, v))
}

// FullNameIn applies the In predicate on the "full_name" field.
func FullNameIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldFullName, vs...))
}

// FullNameNotIn applies the NotIn predicate on the "full_name" field.
func FullNameNotIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldFullName, vs...))
}

// FullNameGT applies the GT predicate on the "full_name" field.
func FullNameGT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldFullName, v))
}

// FullNameGTE applies the GTE predicate on the "full_name" field.
func FullNameGTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldFullName, v))
}

// FullNameLT applies the LT predicate on the "full_name" field.
func FullNameLT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldFullName, v))
}

// FullNameLTE applies the LTE predicate on the "full_name" field.
func FullNameLTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldFullName, v))
}

// FullNameContains applies the Contains predicate on the "full_name" field.
func FullNameContains(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContains(FieldFullName, v))
}

// FullNameHasPrefix applies the HasPrefix predicate on the "full_name" field.
func FullNameHasPrefix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasPrefix(FieldFullName, v))
}

// FullNameHasSuffix applies the HasSuffix predicate on the "full_name" field.
func FullNameHasSuffix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasSuffix(FieldFullName, v))
}

// FullNameEqualFold applies the EqualFold predicate on the "full_name" field.
func FullNameEqualFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEqualFold(FieldFullName, v))
}

// FullNameContainsFold applies the ContainsFold predicate on the "full_name" field.
func FullNameContainsFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContainsFold(FieldFullName, v))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldGender, v))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldGender, v))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldGender, vs...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldGender, vs...))
}

// GenderGT applies the GT predicate on the "gender" field.
func GenderGT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldGender, v))
}

// GenderGTE applies the GTE predicate on the "gender" field.
func GenderGTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldGender, v))
}

// GenderLT applies the LT predicate on the "gender" field.
func GenderLT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldGender, v))
}

// GenderLTE applies the LTE predicate on the "gender" field.
func GenderLTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldGender, v))
}

// GenderContains applies the Contains predicate on the "gender" field.
func GenderContains(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContains(FieldGender, v))
}

// GenderHasPrefix applies the HasPrefix predicate on the "gender" field.
func GenderHasPrefix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasPrefix(FieldGender, v))
}

// GenderHasSuffix applies the HasSuffix predicate on the "gender" field.
func GenderHasSuffix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasSuffix(FieldGender, v))
}

// GenderEqualFold applies the EqualFold predicate on the "gender" field.
func GenderEqualFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEqualFold(FieldGender, v))
}

// GenderContainsFold applies the ContainsFold predicate on the "gender" field.
func GenderContainsFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContainsFold(FieldGender, v))
}

// BirthPlaceEQ applies the EQ predicate on the "birth_place" field.
func BirthPlaceEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldBirthPlace, v))
}

// BirthPlaceNEQ applies the NEQ predicate on the "birth_place" field.
func BirthPlaceNEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldBirthPlace, v))
}

// BirthPlaceIn applies the In predicate on the "birth_place" field.
func BirthPlaceIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldBirthPlace, vs...))
}

// BirthPlaceNotIn applies the NotIn predicate on the "birth_place" field.
func BirthPlaceNotIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldBirthPlace, vs...))
}

// BirthPlaceGT applies the GT predicate on the "birth_place" field.
func BirthPlaceGT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldBirthPlace, v))
}

// BirthPlaceGTE applies the GTE predicate on the "birth_place" field.
func BirthPlaceGTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldBirthPlace, v))
}

// BirthPlaceLT applies the LT predicate on the "birth_place" field.
func BirthPlaceLT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldBirthPlace, v))
}

// BirthPlaceLTE applies the LTE predicate on the "birth_place" field.
func BirthPlaceLTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldBirthPlace, v))
}

// BirthPlaceContains applies the Contains predicate on the "birth_place" field.
func BirthPlaceContains(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContains(FieldBirthPlace, v))
}

// BirthPlaceHasPrefix applies the HasPrefix predicate on the "birth_place" field.
func BirthPlaceHasPrefix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasPrefix(FieldBirthPlace, v))
}

// BirthPlaceHasSuffix applies the HasSuffix predicate on the "birth_place" field.
func BirthPlaceHasSuffix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasSuffix(FieldBirthPlace, v))
}

// BirthPlaceEqualFold applies the EqualFold predicate on the "birth_place" field.
func BirthPlaceEqualFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEqualFold(FieldBirthPlace, v))
}

// BirthPlaceContainsFold applies the ContainsFold predicate on the "birth_place" field.
func BirthPlaceContainsFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContainsFold(FieldBirthPlace, v))
}

// BirthDateEQ applies the EQ predicate on the "birth_date" field.
func BirthDateEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldBirthDate, v))
}

// BirthDateNEQ applies the NEQ predicate on the "birth_date" field.
func BirthDateNEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldBirthDate, v))
}

// BirthDateIn applies the In predicate on the "birth_date" field.
func BirthDateIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldBirthDate, vs...))
}

// BirthDateNotIn applies the NotIn predicate on the "birth_date" field.
func BirthDateNotIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldBirthDate, vs...))
}

// BirthDateGT applies the GT predicate on the "birth_date" field.
func BirthDateGT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldBirthDate, v))
}

// BirthDateGTE applies the GTE predicate on the "birth_date" field.
func BirthDateGTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldBirthDate, v))
}

// BirthDateLT applies the LT predicate on the "birth_date" field.
func BirthDateLT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldBirthDate, v))
}

// BirthDateLTE applies the LTE predicate on the "birth_date" field.
func BirthDateLTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldBirthDate, v))
}

// EmploymentStatusEQ applies the EQ predicate on the "employment_status" field.
func EmploymentStatusEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldEmploymentStatus, v))
}

// EmploymentStatusNEQ applies the NEQ predicate on the "employment_status" field.
func EmploymentStatusNEQ(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldEmploymentStatus, v))
}

// EmploymentStatusIn applies the In predicate on the "employment_status" field.
func EmploymentStatusIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldEmploymentStatus, vs...))
}

// EmploymentStatusNotIn applies the NotIn predicate on the "employment_status" field.
func EmploymentStatusNotIn(vs ...string) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldEmploymentStatus, vs...))
}

// EmploymentStatusGT applies the GT predicate on the "employment_status" field.
func EmploymentStatusGT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldEmploymentStatus, v))
}

// EmploymentStatusGTE applies the GTE predicate on the "employment_status" field.
func EmploymentStatusGTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldEmploymentStatus, v))
}

// EmploymentStatusLT applies the LT predicate on the "employment_status" field.
func EmploymentStatusLT(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldEmploymentStatus, v))
}

// EmploymentStatusLTE applies the LTE predicate on the "employment_status" field.
func EmploymentStatusLTE(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldEmploymentStatus, v))
}

// EmploymentStatusContains applies the Contains predicate on the "employment_status" field.
func EmploymentStatusContains(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContains(FieldEmploymentStatus, v))
}

// EmploymentStatusHasPrefix applies the HasPrefix predicate on the "employment_status" field.
func EmploymentStatusHasPrefix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasPrefix(FieldEmploymentStatus, v))
}

// EmploymentStatusHasSuffix applies the HasSuffix predicate on the "employment_status" field.
func EmploymentStatusHasSuffix(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldHasSuffix(FieldEmploymentStatus, v))
}

// EmploymentStatusEqualFold applies the EqualFold predicate on the "employment_status" field.
func EmploymentStatusEqualFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldEqualFold(FieldEmploymentStatus, v))
}

// EmploymentStatusContainsFold applies the ContainsFold predicate on the "employment_status" field.
func EmploymentStatusContainsFold(v string) predicate.Gtk {
	return predicate.Gtk(sql.FieldContainsFold(FieldEmploymentStatus, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldIsActive, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldJoinedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Gtk {
	return predicate.Gtk(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPositions applies the HasEdge predicate on the "positions" edge.
func HasPositions() predicate.Gtk {
	return predicate.Gtk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PositionsTable, PositionsColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.GtkPosition
		step.Edge.Schema = schemaConfig.GtkPosition
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPositionsWith applies the HasEdge predicate on the "positions" edge with a given conditions (other predicates).
func HasPositionsWith(preds ...predicate.GtkPosition) predicate.Gtk {
	return predicate.Gtk(func(s *sql.Selector) {
		step := newPositionsStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.GtkPosition
		step.Edge.Schema = schemaConfig.GtkPosition
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Gtk) predicate.Gtk {
	return predicate.Gtk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Gtk) predicate.Gtk {
	return predicate.Gtk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Gtk) predicate.Gtk {
	return predicate.Gtk(sql.NotPredicates(p))
}
