name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # Sesuaikan dengan versi Go King

    - name: Verify Dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./cmd/api

    - name: Run Vet & Lint
      run: go vet ./...