// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:       "departments",
		Columns:    DepartmentsColumns,
		PrimaryKey: []*schema.Column{DepartmentsColumns[0]},
	}
	// GtksColumns holds the columns for the "gtks" table.
	GtksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID, Unique: true, Nullable: true},
		{Name: "nik", Type: field.TypeString, Unique: true, Size: 16},
		{Name: "nuptk", Type: field.TypeString, Nullable: true, Size: 16},
		{Name: "full_name", Type: field.TypeString},
		{Name: "gender", Type: field.TypeString},
		{Name: "birth_place", Type: field.TypeString},
		{Name: "birth_date", Type: field.TypeTime},
		{Name: "employment_status", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GtksTable holds the schema information for the "gtks" table.
	GtksTable = &schema.Table{
		Name:       "gtks",
		Columns:    GtksColumns,
		PrimaryKey: []*schema.Column{GtksColumns[0]},
	}
	// GtkPositionsColumns holds the columns for the "gtk_positions" table.
	GtkPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "is_primary", Type: field.TypeBool, Default: false},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "department_id", Type: field.TypeUUID},
		{Name: "gtk_id", Type: field.TypeUUID},
	}
	// GtkPositionsTable holds the schema information for the "gtk_positions" table.
	GtkPositionsTable = &schema.Table{
		Name:       "gtk_positions",
		Columns:    GtkPositionsColumns,
		PrimaryKey: []*schema.Column{GtkPositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "gtk_positions_departments_positions",
				Columns:    []*schema.Column{GtkPositionsColumns[5]},
				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "gtk_positions_gtks_positions",
				Columns:    []*schema.Column{GtkPositionsColumns[6]},
				RefColumns: []*schema.Column{GtksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "schema_name", Type: field.TypeString, Unique: true},
		{Name: "domain", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// TenantUsersColumns holds the columns for the "tenant_users" table.
	TenantUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "role", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// TenantUsersTable holds the schema information for the "tenant_users" table.
	TenantUsersTable = &schema.Table{
		Name:       "tenant_users",
		Columns:    TenantUsersColumns,
		PrimaryKey: []*schema.Column{TenantUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenant_users_tenants_tenant_users",
				Columns:    []*schema.Column{TenantUsersColumns[3]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tenant_users_users_tenant_users",
				Columns:    []*schema.Column{TenantUsersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone_number", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DepartmentsTable,
		GtksTable,
		GtkPositionsTable,
		TenantsTable,
		TenantUsersTable,
		UsersTable,
	}
)

func init() {
	GtkPositionsTable.ForeignKeys[0].RefTable = DepartmentsTable
	GtkPositionsTable.ForeignKeys[1].RefTable = GtksTable
	TenantUsersTable.ForeignKeys[0].RefTable = TenantsTable
	TenantUsersTable.ForeignKeys[1].RefTable = UsersTable
}
