// Code generated by ent, DO NOT EDIT.

package gtkposition

import (
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLTE(FieldID, id))
}

// GtkID applies equality check predicate on the "gtk_id" field. It's identical to GtkIDEQ.
func GtkID(v uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldGtkID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldDepartmentID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldTitle, v))
}

// IsPrimary applies equality check predicate on the "is_primary" field. It's identical to IsPrimaryEQ.
func IsPrimary(v bool) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldIsPrimary, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldEndDate, v))
}

// GtkIDEQ applies the EQ predicate on the "gtk_id" field.
func GtkIDEQ(v uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldGtkID, v))
}

// GtkIDNEQ applies the NEQ predicate on the "gtk_id" field.
func GtkIDNEQ(v uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldGtkID, v))
}

// GtkIDIn applies the In predicate on the "gtk_id" field.
func GtkIDIn(vs ...uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIn(FieldGtkID, vs...))
}

// GtkIDNotIn applies the NotIn predicate on the "gtk_id" field.
func GtkIDNotIn(vs ...uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotIn(FieldGtkID, vs...))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...uuid.UUID) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldContainsFold(FieldTitle, v))
}

// IsPrimaryEQ applies the EQ predicate on the "is_primary" field.
func IsPrimaryEQ(v bool) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldIsPrimary, v))
}

// IsPrimaryNEQ applies the NEQ predicate on the "is_primary" field.
func IsPrimaryNEQ(v bool) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldIsPrimary, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.GtkPosition {
	return predicate.GtkPosition(sql.FieldNotNull(FieldEndDate))
}

// HasGtk applies the HasEdge predicate on the "gtk" edge.
func HasGtk() predicate.GtkPosition {
	return predicate.GtkPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GtkTable, GtkColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Gtk
		step.Edge.Schema = schemaConfig.GtkPosition
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGtkWith applies the HasEdge predicate on the "gtk" edge with a given conditions (other predicates).
func HasGtkWith(preds ...predicate.Gtk) predicate.GtkPosition {
	return predicate.GtkPosition(func(s *sql.Selector) {
		step := newGtkStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Gtk
		step.Edge.Schema = schemaConfig.GtkPosition
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.GtkPosition {
	return predicate.GtkPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Department
		step.Edge.Schema = schemaConfig.GtkPosition
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.GtkPosition {
	return predicate.GtkPosition(func(s *sql.Selector) {
		step := newDepartmentStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Department
		step.Edge.Schema = schemaConfig.GtkPosition
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GtkPosition) predicate.GtkPosition {
	return predicate.GtkPosition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GtkPosition) predicate.GtkPosition {
	return predicate.GtkPosition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GtkPosition) predicate.GtkPosition {
	return predicate.GtkPosition(sql.NotPredicates(p))
}
