// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/gtk"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Gtk is the model entity for the Gtk schema.
type Gtk struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key UUID
	ID uuid.UUID `json:"id,omitempty"`
	// Relasi ke public.users jika GTK memiliki akses login sistem
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// Nomor Induk Kependudukan
	Nik string `json:"nik,omitempty"`
	// Opsional, mengakomodasi tenaga pendidik di lingkungan non-formal
	Nuptk *string `json:"nuptk,omitempty"`
	// Nama lengkap GTK
	FullName string `json:"full_name,omitempty"`
	// Jenis kelamin
	Gender string `json:"gender,omitempty"`
	// Tempat lahir
	BirthPlace string `json:"birth_place,omitempty"`
	// Tanggal lahir
	BirthDate time.Time `json:"birth_date,omitempty"`
	// Status kepegawaian: Tetap, Honorer, Pengabdian
	EmploymentStatus string `json:"employment_status,omitempty"`
	// Status aktif GTK
	IsActive bool `json:"is_active,omitempty"`
	// Tanggal bergabung
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Waktu pembuatan record
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Waktu terakhir update record
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GtkQuery when eager-loading is set.
	Edges        GtkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GtkEdges holds the relations/edges for other nodes in the graph.
type GtkEdges struct {
	// Positions holds the value of the positions edge.
	Positions []*GtkPosition `json:"positions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PositionsOrErr returns the Positions value or an error if the edge
// was not loaded in eager-loading.
func (e GtkEdges) PositionsOrErr() ([]*GtkPosition, error) {
	if e.loadedTypes[0] {
		return e.Positions, nil
	}
	return nil, &NotLoadedError{edge: "positions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Gtk) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gtk.FieldUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case gtk.FieldIsActive:
			values[i] = new(sql.NullBool)
		case gtk.FieldNik, gtk.FieldNuptk, gtk.FieldFullName, gtk.FieldGender, gtk.FieldBirthPlace, gtk.FieldEmploymentStatus:
			values[i] = new(sql.NullString)
		case gtk.FieldBirthDate, gtk.FieldJoinedAt, gtk.FieldCreatedAt, gtk.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case gtk.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Gtk fields.
func (_m *Gtk) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gtk.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gtk.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		case gtk.FieldNik:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nik", values[i])
			} else if value.Valid {
				_m.Nik = value.String
			}
		case gtk.FieldNuptk:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nuptk", values[i])
			} else if value.Valid {
				_m.Nuptk = new(string)
				*_m.Nuptk = value.String
			}
		case gtk.FieldFullName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_name", values[i])
			} else if value.Valid {
				_m.FullName = value.String
			}
		case gtk.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				_m.Gender = value.String
			}
		case gtk.FieldBirthPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field birth_place", values[i])
			} else if value.Valid {
				_m.BirthPlace = value.String
			}
		case gtk.FieldBirthDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field birth_date", values[i])
			} else if value.Valid {
				_m.BirthDate = value.Time
			}
		case gtk.FieldEmploymentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field employment_status", values[i])
			} else if value.Valid {
				_m.EmploymentStatus = value.String
			}
		case gtk.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case gtk.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case gtk.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gtk.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Gtk.
// This includes values selected through modifiers, order, etc.
func (_m *Gtk) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPositions queries the "positions" edge of the Gtk entity.
func (_m *Gtk) QueryPositions() *GtkPositionQuery {
	return NewGtkClient(_m.config).QueryPositions(_m)
}

// Update returns a builder for updating this Gtk.
// Note that you need to call Gtk.Unwrap() before calling this method if this Gtk
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Gtk) Update() *GtkUpdateOne {
	return NewGtkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Gtk entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Gtk) Unwrap() *Gtk {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Gtk is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Gtk) String() string {
	var builder strings.Builder
	builder.WriteString("Gtk(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("nik=")
	builder.WriteString(_m.Nik)
	builder.WriteString(", ")
	if v := _m.Nuptk; v != nil {
		builder.WriteString("nuptk=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("full_name=")
	builder.WriteString(_m.FullName)
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(_m.Gender)
	builder.WriteString(", ")
	builder.WriteString("birth_place=")
	builder.WriteString(_m.BirthPlace)
	builder.WriteString(", ")
	builder.WriteString("birth_date=")
	builder.WriteString(_m.BirthDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("employment_status=")
	builder.WriteString(_m.EmploymentStatus)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Gtks is a parsable slice of Gtk.
type Gtks []*Gtk
