// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GtkUpdate is the builder for updating Gtk entities.
type GtkUpdate struct {
	config
	hooks    []Hook
	mutation *GtkMutation
}

// Where appends a list predicates to the GtkUpdate builder.
func (_u *GtkUpdate) Where(ps ...predicate.Gtk) *GtkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GtkUpdate) SetUserID(v uuid.UUID) *GtkUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableUserID(v *uuid.UUID) *GtkUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *GtkUpdate) ClearUserID() *GtkUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetNik sets the "nik" field.
func (_u *GtkUpdate) SetNik(v string) *GtkUpdate {
	_u.mutation.SetNik(v)
	return _u
}

// SetNillableNik sets the "nik" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableNik(v *string) *GtkUpdate {
	if v != nil {
		_u.SetNik(*v)
	}
	return _u
}

// SetNuptk sets the "nuptk" field.
func (_u *GtkUpdate) SetNuptk(v string) *GtkUpdate {
	_u.mutation.SetNuptk(v)
	return _u
}

// SetNillableNuptk sets the "nuptk" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableNuptk(v *string) *GtkUpdate {
	if v != nil {
		_u.SetNuptk(*v)
	}
	return _u
}

// ClearNuptk clears the value of the "nuptk" field.
func (_u *GtkUpdate) ClearNuptk() *GtkUpdate {
	_u.mutation.ClearNuptk()
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *GtkUpdate) SetFullName(v string) *GtkUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableFullName(v *string) *GtkUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *GtkUpdate) SetGender(v string) *GtkUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableGender(v *string) *GtkUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// SetBirthPlace sets the "birth_place" field.
func (_u *GtkUpdate) SetBirthPlace(v string) *GtkUpdate {
	_u.mutation.SetBirthPlace(v)
	return _u
}

// SetNillableBirthPlace sets the "birth_place" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableBirthPlace(v *string) *GtkUpdate {
	if v != nil {
		_u.SetBirthPlace(*v)
	}
	return _u
}

// SetBirthDate sets the "birth_date" field.
func (_u *GtkUpdate) SetBirthDate(v time.Time) *GtkUpdate {
	_u.mutation.SetBirthDate(v)
	return _u
}

// SetNillableBirthDate sets the "birth_date" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableBirthDate(v *time.Time) *GtkUpdate {
	if v != nil {
		_u.SetBirthDate(*v)
	}
	return _u
}

// SetEmploymentStatus sets the "employment_status" field.
func (_u *GtkUpdate) SetEmploymentStatus(v string) *GtkUpdate {
	_u.mutation.SetEmploymentStatus(v)
	return _u
}

// SetNillableEmploymentStatus sets the "employment_status" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableEmploymentStatus(v *string) *GtkUpdate {
	if v != nil {
		_u.SetEmploymentStatus(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *GtkUpdate) SetIsActive(v bool) *GtkUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableIsActive(v *bool) *GtkUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *GtkUpdate) SetJoinedAt(v time.Time) *GtkUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *GtkUpdate) SetNillableJoinedAt(v *time.Time) *GtkUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GtkUpdate) SetUpdatedAt(v time.Time) *GtkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPositionIDs adds the "positions" edge to the GtkPosition entity by IDs.
func (_u *GtkUpdate) AddPositionIDs(ids ...uuid.UUID) *GtkUpdate {
	_u.mutation.AddPositionIDs(ids...)
	return _u
}

// AddPositions adds the "positions" edges to the GtkPosition entity.
func (_u *GtkUpdate) AddPositions(v ...*GtkPosition) *GtkUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPositionIDs(ids...)
}

// Mutation returns the GtkMutation object of the builder.
func (_u *GtkUpdate) Mutation() *GtkMutation {
	return _u.mutation
}

// ClearPositions clears all "positions" edges to the GtkPosition entity.
func (_u *GtkUpdate) ClearPositions() *GtkUpdate {
	_u.mutation.ClearPositions()
	return _u
}

// RemovePositionIDs removes the "positions" edge to GtkPosition entities by IDs.
func (_u *GtkUpdate) RemovePositionIDs(ids ...uuid.UUID) *GtkUpdate {
	_u.mutation.RemovePositionIDs(ids...)
	return _u
}

// RemovePositions removes "positions" edges to GtkPosition entities.
func (_u *GtkUpdate) RemovePositions(v ...*GtkPosition) *GtkUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePositionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GtkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GtkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GtkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GtkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GtkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gtk.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GtkUpdate) check() error {
	if v, ok := _u.mutation.Nik(); ok {
		if err := gtk.NikValidator(v); err != nil {
			return &ValidationError{Name: "nik", err: fmt.Errorf(`ent: validator failed for field "Gtk.nik": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nuptk(); ok {
		if err := gtk.NuptkValidator(v); err != nil {
			return &ValidationError{Name: "nuptk", err: fmt.Errorf(`ent: validator failed for field "Gtk.nuptk": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := gtk.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Gtk.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := gtk.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Gtk.gender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BirthPlace(); ok {
		if err := gtk.BirthPlaceValidator(v); err != nil {
			return &ValidationError{Name: "birth_place", err: fmt.Errorf(`ent: validator failed for field "Gtk.birth_place": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmploymentStatus(); ok {
		if err := gtk.EmploymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "employment_status", err: fmt.Errorf(`ent: validator failed for field "Gtk.employment_status": %w`, err)}
		}
	}
	return nil
}

func (_u *GtkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gtk.Table, gtk.Columns, sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(gtk.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(gtk.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Nik(); ok {
		_spec.SetField(gtk.FieldNik, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nuptk(); ok {
		_spec.SetField(gtk.FieldNuptk, field.TypeString, value)
	}
	if _u.mutation.NuptkCleared() {
		_spec.ClearField(gtk.FieldNuptk, field.TypeString)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(gtk.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(gtk.FieldGender, field.TypeString, value)
	}
	if value, ok := _u.mutation.BirthPlace(); ok {
		_spec.SetField(gtk.FieldBirthPlace, field.TypeString, value)
	}
	if value, ok := _u.mutation.BirthDate(); ok {
		_spec.SetField(gtk.FieldBirthDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EmploymentStatus(); ok {
		_spec.SetField(gtk.FieldEmploymentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(gtk.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(gtk.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gtk.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPositionsIDs(); len(nodes) > 0 && !_u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Gtk
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gtk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GtkUpdateOne is the builder for updating a single Gtk entity.
type GtkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GtkMutation
}

// SetUserID sets the "user_id" field.
func (_u *GtkUpdateOne) SetUserID(v uuid.UUID) *GtkUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableUserID(v *uuid.UUID) *GtkUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *GtkUpdateOne) ClearUserID() *GtkUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetNik sets the "nik" field.
func (_u *GtkUpdateOne) SetNik(v string) *GtkUpdateOne {
	_u.mutation.SetNik(v)
	return _u
}

// SetNillableNik sets the "nik" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableNik(v *string) *GtkUpdateOne {
	if v != nil {
		_u.SetNik(*v)
	}
	return _u
}

// SetNuptk sets the "nuptk" field.
func (_u *GtkUpdateOne) SetNuptk(v string) *GtkUpdateOne {
	_u.mutation.SetNuptk(v)
	return _u
}

// SetNillableNuptk sets the "nuptk" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableNuptk(v *string) *GtkUpdateOne {
	if v != nil {
		_u.SetNuptk(*v)
	}
	return _u
}

// ClearNuptk clears the value of the "nuptk" field.
func (_u *GtkUpdateOne) ClearNuptk() *GtkUpdateOne {
	_u.mutation.ClearNuptk()
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *GtkUpdateOne) SetFullName(v string) *GtkUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableFullName(v *string) *GtkUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *GtkUpdateOne) SetGender(v string) *GtkUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableGender(v *string) *GtkUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// SetBirthPlace sets the "birth_place" field.
func (_u *GtkUpdateOne) SetBirthPlace(v string) *GtkUpdateOne {
	_u.mutation.SetBirthPlace(v)
	return _u
}

// SetNillableBirthPlace sets the "birth_place" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableBirthPlace(v *string) *GtkUpdateOne {
	if v != nil {
		_u.SetBirthPlace(*v)
	}
	return _u
}

// SetBirthDate sets the "birth_date" field.
func (_u *GtkUpdateOne) SetBirthDate(v time.Time) *GtkUpdateOne {
	_u.mutation.SetBirthDate(v)
	return _u
}

// SetNillableBirthDate sets the "birth_date" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableBirthDate(v *time.Time) *GtkUpdateOne {
	if v != nil {
		_u.SetBirthDate(*v)
	}
	return _u
}

// SetEmploymentStatus sets the "employment_status" field.
func (_u *GtkUpdateOne) SetEmploymentStatus(v string) *GtkUpdateOne {
	_u.mutation.SetEmploymentStatus(v)
	return _u
}

// SetNillableEmploymentStatus sets the "employment_status" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableEmploymentStatus(v *string) *GtkUpdateOne {
	if v != nil {
		_u.SetEmploymentStatus(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *GtkUpdateOne) SetIsActive(v bool) *GtkUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableIsActive(v *bool) *GtkUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *GtkUpdateOne) SetJoinedAt(v time.Time) *GtkUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *GtkUpdateOne) SetNillableJoinedAt(v *time.Time) *GtkUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GtkUpdateOne) SetUpdatedAt(v time.Time) *GtkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPositionIDs adds the "positions" edge to the GtkPosition entity by IDs.
func (_u *GtkUpdateOne) AddPositionIDs(ids ...uuid.UUID) *GtkUpdateOne {
	_u.mutation.AddPositionIDs(ids...)
	return _u
}

// AddPositions adds the "positions" edges to the GtkPosition entity.
func (_u *GtkUpdateOne) AddPositions(v ...*GtkPosition) *GtkUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPositionIDs(ids...)
}

// Mutation returns the GtkMutation object of the builder.
func (_u *GtkUpdateOne) Mutation() *GtkMutation {
	return _u.mutation
}

// ClearPositions clears all "positions" edges to the GtkPosition entity.
func (_u *GtkUpdateOne) ClearPositions() *GtkUpdateOne {
	_u.mutation.ClearPositions()
	return _u
}

// RemovePositionIDs removes the "positions" edge to GtkPosition entities by IDs.
func (_u *GtkUpdateOne) RemovePositionIDs(ids ...uuid.UUID) *GtkUpdateOne {
	_u.mutation.RemovePositionIDs(ids...)
	return _u
}

// RemovePositions removes "positions" edges to GtkPosition entities.
func (_u *GtkUpdateOne) RemovePositions(v ...*GtkPosition) *GtkUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePositionIDs(ids...)
}

// Where appends a list predicates to the GtkUpdate builder.
func (_u *GtkUpdateOne) Where(ps ...predicate.Gtk) *GtkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GtkUpdateOne) Select(field string, fields ...string) *GtkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Gtk entity.
func (_u *GtkUpdateOne) Save(ctx context.Context) (*Gtk, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GtkUpdateOne) SaveX(ctx context.Context) *Gtk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GtkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GtkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GtkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gtk.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GtkUpdateOne) check() error {
	if v, ok := _u.mutation.Nik(); ok {
		if err := gtk.NikValidator(v); err != nil {
			return &ValidationError{Name: "nik", err: fmt.Errorf(`ent: validator failed for field "Gtk.nik": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nuptk(); ok {
		if err := gtk.NuptkValidator(v); err != nil {
			return &ValidationError{Name: "nuptk", err: fmt.Errorf(`ent: validator failed for field "Gtk.nuptk": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := gtk.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Gtk.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := gtk.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Gtk.gender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BirthPlace(); ok {
		if err := gtk.BirthPlaceValidator(v); err != nil {
			return &ValidationError{Name: "birth_place", err: fmt.Errorf(`ent: validator failed for field "Gtk.birth_place": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmploymentStatus(); ok {
		if err := gtk.EmploymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "employment_status", err: fmt.Errorf(`ent: validator failed for field "Gtk.employment_status": %w`, err)}
		}
	}
	return nil
}

func (_u *GtkUpdateOne) sqlSave(ctx context.Context) (_node *Gtk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gtk.Table, gtk.Columns, sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Gtk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gtk.FieldID)
		for _, f := range fields {
			if !gtk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gtk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(gtk.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(gtk.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Nik(); ok {
		_spec.SetField(gtk.FieldNik, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nuptk(); ok {
		_spec.SetField(gtk.FieldNuptk, field.TypeString, value)
	}
	if _u.mutation.NuptkCleared() {
		_spec.ClearField(gtk.FieldNuptk, field.TypeString)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(gtk.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(gtk.FieldGender, field.TypeString, value)
	}
	if value, ok := _u.mutation.BirthPlace(); ok {
		_spec.SetField(gtk.FieldBirthPlace, field.TypeString, value)
	}
	if value, ok := _u.mutation.BirthDate(); ok {
		_spec.SetField(gtk.FieldBirthDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EmploymentStatus(); ok {
		_spec.SetField(gtk.FieldEmploymentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(gtk.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(gtk.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gtk.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPositionsIDs(); len(nodes) > 0 && !_u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Gtk
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Gtk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gtk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
