// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GtkQuery is the builder for querying Gtk entities.
type GtkQuery struct {
	config
	ctx           *QueryContext
	order         []gtk.OrderOption
	inters        []Interceptor
	predicates    []predicate.Gtk
	withPositions *GtkPositionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GtkQuery builder.
func (_q *GtkQuery) Where(ps ...predicate.Gtk) *GtkQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GtkQuery) Limit(limit int) *GtkQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GtkQuery) Offset(offset int) *GtkQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GtkQuery) Unique(unique bool) *GtkQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GtkQuery) Order(o ...gtk.OrderOption) *GtkQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPositions chains the current query on the "positions" edge.
func (_q *GtkQuery) QueryPositions() *GtkPositionQuery {
	query := (&GtkPositionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gtk.Table, gtk.FieldID, selector),
			sqlgraph.To(gtkposition.Table, gtkposition.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, gtk.PositionsTable, gtk.PositionsColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.GtkPosition
		step.Edge.Schema = schemaConfig.GtkPosition
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Gtk entity from the query.
// Returns a *NotFoundError when no Gtk was found.
func (_q *GtkQuery) First(ctx context.Context) (*Gtk, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gtk.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GtkQuery) FirstX(ctx context.Context) *Gtk {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Gtk ID from the query.
// Returns a *NotFoundError when no Gtk ID was found.
func (_q *GtkQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gtk.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GtkQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Gtk entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Gtk entity is found.
// Returns a *NotFoundError when no Gtk entities are found.
func (_q *GtkQuery) Only(ctx context.Context) (*Gtk, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gtk.Label}
	default:
		return nil, &NotSingularError{gtk.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GtkQuery) OnlyX(ctx context.Context) *Gtk {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Gtk ID in the query.
// Returns a *NotSingularError when more than one Gtk ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GtkQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gtk.Label}
	default:
		err = &NotSingularError{gtk.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GtkQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Gtks.
func (_q *GtkQuery) All(ctx context.Context) ([]*Gtk, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Gtk, *GtkQuery]()
	return withInterceptors[[]*Gtk](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GtkQuery) AllX(ctx context.Context) []*Gtk {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Gtk IDs.
func (_q *GtkQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(gtk.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GtkQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GtkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GtkQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GtkQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GtkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GtkQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GtkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GtkQuery) Clone() *GtkQuery {
	if _q == nil {
		return nil
	}
	return &GtkQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]gtk.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Gtk{}, _q.predicates...),
		withPositions: _q.withPositions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPositions tells the query-builder to eager-load the nodes that are connected to
// the "positions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GtkQuery) WithPositions(opts ...func(*GtkPositionQuery)) *GtkQuery {
	query := (&GtkPositionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPositions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Gtk.Query().
//		GroupBy(gtk.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GtkQuery) GroupBy(field string, fields ...string) *GtkGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GtkGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = gtk.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.Gtk.Query().
//		Select(gtk.FieldUserID).
//		Scan(ctx, &v)
func (_q *GtkQuery) Select(fields ...string) *GtkSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GtkSelect{GtkQuery: _q}
	sbuild.label = gtk.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GtkSelect configured with the given aggregations.
func (_q *GtkQuery) Aggregate(fns ...AggregateFunc) *GtkSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GtkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !gtk.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GtkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Gtk, error) {
	var (
		nodes       = []*Gtk{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withPositions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Gtk).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Gtk{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.Gtk
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPositions; query != nil {
		if err := _q.loadPositions(ctx, query, nodes,
			func(n *Gtk) { n.Edges.Positions = []*GtkPosition{} },
			func(n *Gtk, e *GtkPosition) { n.Edges.Positions = append(n.Edges.Positions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GtkQuery) loadPositions(ctx context.Context, query *GtkPositionQuery, nodes []*Gtk, init func(*Gtk), assign func(*Gtk, *GtkPosition)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Gtk)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(gtkposition.FieldGtkID)
	}
	query.Where(predicate.GtkPosition(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(gtk.PositionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GtkID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "gtk_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *GtkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.Gtk
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GtkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gtk.Table, gtk.Columns, sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gtk.FieldID)
		for i := range fields {
			if fields[i] != gtk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GtkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(gtk.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = gtk.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.Gtk)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GtkGroupBy is the group-by builder for Gtk entities.
type GtkGroupBy struct {
	selector
	build *GtkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GtkGroupBy) Aggregate(fns ...AggregateFunc) *GtkGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GtkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GtkQuery, *GtkGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GtkGroupBy) sqlScan(ctx context.Context, root *GtkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GtkSelect is the builder for selecting fields of Gtk entities.
type GtkSelect struct {
	*GtkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GtkSelect) Aggregate(fns ...AggregateFunc) *GtkSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GtkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GtkQuery, *GtkSelect](ctx, _s.GtkQuery, _s, _s.inters, v)
}

func (_s *GtkSelect) sqlScan(ctx context.Context, root *GtkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
