// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GtkCreate is the builder for creating a Gtk entity.
type GtkCreate struct {
	config
	mutation *GtkMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *GtkCreate) SetUserID(v uuid.UUID) *GtkCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *GtkCreate) SetNillableUserID(v *uuid.UUID) *GtkCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetNik sets the "nik" field.
func (_c *GtkCreate) SetNik(v string) *GtkCreate {
	_c.mutation.SetNik(v)
	return _c
}

// SetNuptk sets the "nuptk" field.
func (_c *GtkCreate) SetNuptk(v string) *GtkCreate {
	_c.mutation.SetNuptk(v)
	return _c
}

// SetNillableNuptk sets the "nuptk" field if the given value is not nil.
func (_c *GtkCreate) SetNillableNuptk(v *string) *GtkCreate {
	if v != nil {
		_c.SetNuptk(*v)
	}
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *GtkCreate) SetFullName(v string) *GtkCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetGender sets the "gender" field.
func (_c *GtkCreate) SetGender(v string) *GtkCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetBirthPlace sets the "birth_place" field.
func (_c *GtkCreate) SetBirthPlace(v string) *GtkCreate {
	_c.mutation.SetBirthPlace(v)
	return _c
}

// SetBirthDate sets the "birth_date" field.
func (_c *GtkCreate) SetBirthDate(v time.Time) *GtkCreate {
	_c.mutation.SetBirthDate(v)
	return _c
}

// SetEmploymentStatus sets the "employment_status" field.
func (_c *GtkCreate) SetEmploymentStatus(v string) *GtkCreate {
	_c.mutation.SetEmploymentStatus(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *GtkCreate) SetIsActive(v bool) *GtkCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *GtkCreate) SetNillableIsActive(v *bool) *GtkCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *GtkCreate) SetJoinedAt(v time.Time) *GtkCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GtkCreate) SetCreatedAt(v time.Time) *GtkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GtkCreate) SetNillableCreatedAt(v *time.Time) *GtkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GtkCreate) SetUpdatedAt(v time.Time) *GtkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GtkCreate) SetNillableUpdatedAt(v *time.Time) *GtkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GtkCreate) SetID(v uuid.UUID) *GtkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GtkCreate) SetNillableID(v *uuid.UUID) *GtkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPositionIDs adds the "positions" edge to the GtkPosition entity by IDs.
func (_c *GtkCreate) AddPositionIDs(ids ...uuid.UUID) *GtkCreate {
	_c.mutation.AddPositionIDs(ids...)
	return _c
}

// AddPositions adds the "positions" edges to the GtkPosition entity.
func (_c *GtkCreate) AddPositions(v ...*GtkPosition) *GtkCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPositionIDs(ids...)
}

// Mutation returns the GtkMutation object of the builder.
func (_c *GtkCreate) Mutation() *GtkMutation {
	return _c.mutation
}

// Save creates the Gtk in the database.
func (_c *GtkCreate) Save(ctx context.Context) (*Gtk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GtkCreate) SaveX(ctx context.Context) *Gtk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GtkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GtkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GtkCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := gtk.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gtk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gtk.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := gtk.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GtkCreate) check() error {
	if _, ok := _c.mutation.Nik(); !ok {
		return &ValidationError{Name: "nik", err: errors.New(`ent: missing required field "Gtk.nik"`)}
	}
	if v, ok := _c.mutation.Nik(); ok {
		if err := gtk.NikValidator(v); err != nil {
			return &ValidationError{Name: "nik", err: fmt.Errorf(`ent: validator failed for field "Gtk.nik": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Nuptk(); ok {
		if err := gtk.NuptkValidator(v); err != nil {
			return &ValidationError{Name: "nuptk", err: fmt.Errorf(`ent: validator failed for field "Gtk.nuptk": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "Gtk.full_name"`)}
	}
	if v, ok := _c.mutation.FullName(); ok {
		if err := gtk.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Gtk.full_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Gender(); !ok {
		return &ValidationError{Name: "gender", err: errors.New(`ent: missing required field "Gtk.gender"`)}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := gtk.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Gtk.gender": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BirthPlace(); !ok {
		return &ValidationError{Name: "birth_place", err: errors.New(`ent: missing required field "Gtk.birth_place"`)}
	}
	if v, ok := _c.mutation.BirthPlace(); ok {
		if err := gtk.BirthPlaceValidator(v); err != nil {
			return &ValidationError{Name: "birth_place", err: fmt.Errorf(`ent: validator failed for field "Gtk.birth_place": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BirthDate(); !ok {
		return &ValidationError{Name: "birth_date", err: errors.New(`ent: missing required field "Gtk.birth_date"`)}
	}
	if _, ok := _c.mutation.EmploymentStatus(); !ok {
		return &ValidationError{Name: "employment_status", err: errors.New(`ent: missing required field "Gtk.employment_status"`)}
	}
	if v, ok := _c.mutation.EmploymentStatus(); ok {
		if err := gtk.EmploymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "employment_status", err: fmt.Errorf(`ent: validator failed for field "Gtk.employment_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Gtk.is_active"`)}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "Gtk.joined_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Gtk.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Gtk.updated_at"`)}
	}
	return nil
}

func (_c *GtkCreate) sqlSave(ctx context.Context) (*Gtk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GtkCreate) createSpec() (*Gtk, *sqlgraph.CreateSpec) {
	var (
		_node = &Gtk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gtk.Table, sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Gtk
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(gtk.FieldUserID, field.TypeUUID, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Nik(); ok {
		_spec.SetField(gtk.FieldNik, field.TypeString, value)
		_node.Nik = value
	}
	if value, ok := _c.mutation.Nuptk(); ok {
		_spec.SetField(gtk.FieldNuptk, field.TypeString, value)
		_node.Nuptk = &value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(gtk.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(gtk.FieldGender, field.TypeString, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.BirthPlace(); ok {
		_spec.SetField(gtk.FieldBirthPlace, field.TypeString, value)
		_node.BirthPlace = value
	}
	if value, ok := _c.mutation.BirthDate(); ok {
		_spec.SetField(gtk.FieldBirthDate, field.TypeTime, value)
		_node.BirthDate = value
	}
	if value, ok := _c.mutation.EmploymentStatus(); ok {
		_spec.SetField(gtk.FieldEmploymentStatus, field.TypeString, value)
		_node.EmploymentStatus = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(gtk.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(gtk.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gtk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gtk.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gtk.PositionsTable,
			Columns: []string{gtk.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GtkCreateBulk is the builder for creating many Gtk entities in bulk.
type GtkCreateBulk struct {
	config
	err      error
	builders []*GtkCreate
}

// Save creates the Gtk entities in the database.
func (_c *GtkCreateBulk) Save(ctx context.Context) ([]*Gtk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Gtk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GtkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GtkCreateBulk) SaveX(ctx context.Context) []*Gtk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GtkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GtkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
