// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/gtkposition"
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GtkPositionDelete is the builder for deleting a GtkPosition entity.
type GtkPositionDelete struct {
	config
	hooks    []Hook
	mutation *GtkPositionMutation
}

// Where appends a list predicates to the GtkPositionDelete builder.
func (_d *GtkPositionDelete) Where(ps ...predicate.GtkPosition) *GtkPositionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GtkPositionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GtkPositionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GtkPositionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gtkposition.Table, sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.GtkPosition
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GtkPositionDeleteOne is the builder for deleting a single GtkPosition entity.
type GtkPositionDeleteOne struct {
	_d *GtkPositionDelete
}

// Where appends a list predicates to the GtkPositionDelete builder.
func (_d *GtkPositionDeleteOne) Where(ps ...predicate.GtkPosition) *GtkPositionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GtkPositionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gtkposition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GtkPositionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
