// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/department"
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GtkPositionCreate is the builder for creating a GtkPosition entity.
type GtkPositionCreate struct {
	config
	mutation *GtkPositionMutation
	hooks    []Hook
}

// SetGtkID sets the "gtk_id" field.
func (_c *GtkPositionCreate) SetGtkID(v uuid.UUID) *GtkPositionCreate {
	_c.mutation.SetGtkID(v)
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *GtkPositionCreate) SetDepartmentID(v uuid.UUID) *GtkPositionCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *GtkPositionCreate) SetTitle(v string) *GtkPositionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetIsPrimary sets the "is_primary" field.
func (_c *GtkPositionCreate) SetIsPrimary(v bool) *GtkPositionCreate {
	_c.mutation.SetIsPrimary(v)
	return _c
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_c *GtkPositionCreate) SetNillableIsPrimary(v *bool) *GtkPositionCreate {
	if v != nil {
		_c.SetIsPrimary(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *GtkPositionCreate) SetStartDate(v time.Time) *GtkPositionCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *GtkPositionCreate) SetEndDate(v time.Time) *GtkPositionCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *GtkPositionCreate) SetNillableEndDate(v *time.Time) *GtkPositionCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GtkPositionCreate) SetID(v uuid.UUID) *GtkPositionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GtkPositionCreate) SetNillableID(v *uuid.UUID) *GtkPositionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGtk sets the "gtk" edge to the Gtk entity.
func (_c *GtkPositionCreate) SetGtk(v *Gtk) *GtkPositionCreate {
	return _c.SetGtkID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_c *GtkPositionCreate) SetDepartment(v *Department) *GtkPositionCreate {
	return _c.SetDepartmentID(v.ID)
}

// Mutation returns the GtkPositionMutation object of the builder.
func (_c *GtkPositionCreate) Mutation() *GtkPositionMutation {
	return _c.mutation
}

// Save creates the GtkPosition in the database.
func (_c *GtkPositionCreate) Save(ctx context.Context) (*GtkPosition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GtkPositionCreate) SaveX(ctx context.Context) *GtkPosition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GtkPositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GtkPositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GtkPositionCreate) defaults() {
	if _, ok := _c.mutation.IsPrimary(); !ok {
		v := gtkposition.DefaultIsPrimary
		_c.mutation.SetIsPrimary(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := gtkposition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GtkPositionCreate) check() error {
	if _, ok := _c.mutation.GtkID(); !ok {
		return &ValidationError{Name: "gtk_id", err: errors.New(`ent: missing required field "GtkPosition.gtk_id"`)}
	}
	if _, ok := _c.mutation.DepartmentID(); !ok {
		return &ValidationError{Name: "department_id", err: errors.New(`ent: missing required field "GtkPosition.department_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "GtkPosition.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := gtkposition.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GtkPosition.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		return &ValidationError{Name: "is_primary", err: errors.New(`ent: missing required field "GtkPosition.is_primary"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "GtkPosition.start_date"`)}
	}
	if len(_c.mutation.GtkIDs()) == 0 {
		return &ValidationError{Name: "gtk", err: errors.New(`ent: missing required edge "GtkPosition.gtk"`)}
	}
	if len(_c.mutation.DepartmentIDs()) == 0 {
		return &ValidationError{Name: "department", err: errors.New(`ent: missing required edge "GtkPosition.department"`)}
	}
	return nil
}

func (_c *GtkPositionCreate) sqlSave(ctx context.Context) (*GtkPosition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GtkPositionCreate) createSpec() (*GtkPosition, *sqlgraph.CreateSpec) {
	var (
		_node = &GtkPosition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gtkposition.Table, sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.GtkPosition
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(gtkposition.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.IsPrimary(); ok {
		_spec.SetField(gtkposition.FieldIsPrimary, field.TypeBool, value)
		_node.IsPrimary = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(gtkposition.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(gtkposition.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if nodes := _c.mutation.GtkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.GtkTable,
			Columns: []string{gtkposition.GtkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GtkID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.DepartmentTable,
			Columns: []string{gtkposition.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DepartmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GtkPositionCreateBulk is the builder for creating many GtkPosition entities in bulk.
type GtkPositionCreateBulk struct {
	config
	err      error
	builders []*GtkPositionCreate
}

// Save creates the GtkPosition entities in the database.
func (_c *GtkPositionCreateBulk) Save(ctx context.Context) ([]*GtkPosition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GtkPosition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GtkPositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GtkPositionCreateBulk) SaveX(ctx context.Context) []*GtkPosition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GtkPositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GtkPositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
