// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/department"
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// GtkPosition is the model entity for the GtkPosition schema.
type GtkPosition struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key UUID
	ID uuid.UUID `json:"id,omitempty"`
	// Foreign key ke tabel gtk
	GtkID uuid.UUID `json:"gtk_id,omitempty"`
	// Foreign key ke tabel departments
	DepartmentID uuid.UUID `json:"department_id,omitempty"`
	// Jabatan: Kepala Pondok, Operator, Musyrif
	Title string `json:"title,omitempty"`
	// Menandakan jabatan utama jika GTK merangkap tugas
	IsPrimary bool `json:"is_primary,omitempty"`
	// Tanggal mulai menjabat
	StartDate time.Time `json:"start_date,omitempty"`
	// Tanggal selesai menjabat (null jika masih aktif)
	EndDate *time.Time `json:"end_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GtkPositionQuery when eager-loading is set.
	Edges        GtkPositionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GtkPositionEdges holds the relations/edges for other nodes in the graph.
type GtkPositionEdges struct {
	// Gtk holds the value of the gtk edge.
	Gtk *Gtk `json:"gtk,omitempty"`
	// Department holds the value of the department edge.
	Department *Department `json:"department,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GtkOrErr returns the Gtk value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GtkPositionEdges) GtkOrErr() (*Gtk, error) {
	if e.Gtk != nil {
		return e.Gtk, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: gtk.Label}
	}
	return nil, &NotLoadedError{edge: "gtk"}
}

// DepartmentOrErr returns the Department value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GtkPositionEdges) DepartmentOrErr() (*Department, error) {
	if e.Department != nil {
		return e.Department, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: department.Label}
	}
	return nil, &NotLoadedError{edge: "department"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GtkPosition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gtkposition.FieldIsPrimary:
			values[i] = new(sql.NullBool)
		case gtkposition.FieldTitle:
			values[i] = new(sql.NullString)
		case gtkposition.FieldStartDate, gtkposition.FieldEndDate:
			values[i] = new(sql.NullTime)
		case gtkposition.FieldID, gtkposition.FieldGtkID, gtkposition.FieldDepartmentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GtkPosition fields.
func (_m *GtkPosition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gtkposition.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gtkposition.FieldGtkID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field gtk_id", values[i])
			} else if value != nil {
				_m.GtkID = *value
			}
		case gtkposition.FieldDepartmentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value != nil {
				_m.DepartmentID = *value
			}
		case gtkposition.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case gtkposition.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				_m.IsPrimary = value.Bool
			}
		case gtkposition.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case gtkposition.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GtkPosition.
// This includes values selected through modifiers, order, etc.
func (_m *GtkPosition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGtk queries the "gtk" edge of the GtkPosition entity.
func (_m *GtkPosition) QueryGtk() *GtkQuery {
	return NewGtkPositionClient(_m.config).QueryGtk(_m)
}

// QueryDepartment queries the "department" edge of the GtkPosition entity.
func (_m *GtkPosition) QueryDepartment() *DepartmentQuery {
	return NewGtkPositionClient(_m.config).QueryDepartment(_m)
}

// Update returns a builder for updating this GtkPosition.
// Note that you need to call GtkPosition.Unwrap() before calling this method if this GtkPosition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GtkPosition) Update() *GtkPositionUpdateOne {
	return NewGtkPositionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GtkPosition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GtkPosition) Unwrap() *GtkPosition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GtkPosition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GtkPosition) String() string {
	var builder strings.Builder
	builder.WriteString("GtkPosition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("gtk_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GtkID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("is_primary=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPrimary))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GtkPositions is a parsable slice of GtkPosition.
type GtkPositions []*GtkPosition
