// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/department"
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GtkPositionUpdate is the builder for updating GtkPosition entities.
type GtkPositionUpdate struct {
	config
	hooks    []Hook
	mutation *GtkPositionMutation
}

// Where appends a list predicates to the GtkPositionUpdate builder.
func (_u *GtkPositionUpdate) Where(ps ...predicate.GtkPosition) *GtkPositionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGtkID sets the "gtk_id" field.
func (_u *GtkPositionUpdate) SetGtkID(v uuid.UUID) *GtkPositionUpdate {
	_u.mutation.SetGtkID(v)
	return _u
}

// SetNillableGtkID sets the "gtk_id" field if the given value is not nil.
func (_u *GtkPositionUpdate) SetNillableGtkID(v *uuid.UUID) *GtkPositionUpdate {
	if v != nil {
		_u.SetGtkID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *GtkPositionUpdate) SetDepartmentID(v uuid.UUID) *GtkPositionUpdate {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *GtkPositionUpdate) SetNillableDepartmentID(v *uuid.UUID) *GtkPositionUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *GtkPositionUpdate) SetTitle(v string) *GtkPositionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GtkPositionUpdate) SetNillableTitle(v *string) *GtkPositionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *GtkPositionUpdate) SetIsPrimary(v bool) *GtkPositionUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *GtkPositionUpdate) SetNillableIsPrimary(v *bool) *GtkPositionUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *GtkPositionUpdate) SetStartDate(v time.Time) *GtkPositionUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *GtkPositionUpdate) SetNillableStartDate(v *time.Time) *GtkPositionUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *GtkPositionUpdate) SetEndDate(v time.Time) *GtkPositionUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *GtkPositionUpdate) SetNillableEndDate(v *time.Time) *GtkPositionUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *GtkPositionUpdate) ClearEndDate() *GtkPositionUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetGtk sets the "gtk" edge to the Gtk entity.
func (_u *GtkPositionUpdate) SetGtk(v *Gtk) *GtkPositionUpdate {
	return _u.SetGtkID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *GtkPositionUpdate) SetDepartment(v *Department) *GtkPositionUpdate {
	return _u.SetDepartmentID(v.ID)
}

// Mutation returns the GtkPositionMutation object of the builder.
func (_u *GtkPositionUpdate) Mutation() *GtkPositionMutation {
	return _u.mutation
}

// ClearGtk clears the "gtk" edge to the Gtk entity.
func (_u *GtkPositionUpdate) ClearGtk() *GtkPositionUpdate {
	_u.mutation.ClearGtk()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *GtkPositionUpdate) ClearDepartment() *GtkPositionUpdate {
	_u.mutation.ClearDepartment()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GtkPositionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GtkPositionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GtkPositionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GtkPositionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GtkPositionUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := gtkposition.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GtkPosition.title": %w`, err)}
		}
	}
	if _u.mutation.GtkCleared() && len(_u.mutation.GtkIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GtkPosition.gtk"`)
	}
	if _u.mutation.DepartmentCleared() && len(_u.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GtkPosition.department"`)
	}
	return nil
}

func (_u *GtkPositionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gtkposition.Table, gtkposition.Columns, sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(gtkposition.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(gtkposition.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(gtkposition.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(gtkposition.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(gtkposition.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.GtkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.GtkTable,
			Columns: []string{gtkposition.GtkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GtkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.GtkTable,
			Columns: []string{gtkposition.GtkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.DepartmentTable,
			Columns: []string{gtkposition.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.DepartmentTable,
			Columns: []string{gtkposition.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.GtkPosition
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gtkposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GtkPositionUpdateOne is the builder for updating a single GtkPosition entity.
type GtkPositionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GtkPositionMutation
}

// SetGtkID sets the "gtk_id" field.
func (_u *GtkPositionUpdateOne) SetGtkID(v uuid.UUID) *GtkPositionUpdateOne {
	_u.mutation.SetGtkID(v)
	return _u
}

// SetNillableGtkID sets the "gtk_id" field if the given value is not nil.
func (_u *GtkPositionUpdateOne) SetNillableGtkID(v *uuid.UUID) *GtkPositionUpdateOne {
	if v != nil {
		_u.SetGtkID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *GtkPositionUpdateOne) SetDepartmentID(v uuid.UUID) *GtkPositionUpdateOne {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *GtkPositionUpdateOne) SetNillableDepartmentID(v *uuid.UUID) *GtkPositionUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *GtkPositionUpdateOne) SetTitle(v string) *GtkPositionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GtkPositionUpdateOne) SetNillableTitle(v *string) *GtkPositionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *GtkPositionUpdateOne) SetIsPrimary(v bool) *GtkPositionUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *GtkPositionUpdateOne) SetNillableIsPrimary(v *bool) *GtkPositionUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *GtkPositionUpdateOne) SetStartDate(v time.Time) *GtkPositionUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *GtkPositionUpdateOne) SetNillableStartDate(v *time.Time) *GtkPositionUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *GtkPositionUpdateOne) SetEndDate(v time.Time) *GtkPositionUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *GtkPositionUpdateOne) SetNillableEndDate(v *time.Time) *GtkPositionUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *GtkPositionUpdateOne) ClearEndDate() *GtkPositionUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetGtk sets the "gtk" edge to the Gtk entity.
func (_u *GtkPositionUpdateOne) SetGtk(v *Gtk) *GtkPositionUpdateOne {
	return _u.SetGtkID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *GtkPositionUpdateOne) SetDepartment(v *Department) *GtkPositionUpdateOne {
	return _u.SetDepartmentID(v.ID)
}

// Mutation returns the GtkPositionMutation object of the builder.
func (_u *GtkPositionUpdateOne) Mutation() *GtkPositionMutation {
	return _u.mutation
}

// ClearGtk clears the "gtk" edge to the Gtk entity.
func (_u *GtkPositionUpdateOne) ClearGtk() *GtkPositionUpdateOne {
	_u.mutation.ClearGtk()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *GtkPositionUpdateOne) ClearDepartment() *GtkPositionUpdateOne {
	_u.mutation.ClearDepartment()
	return _u
}

// Where appends a list predicates to the GtkPositionUpdate builder.
func (_u *GtkPositionUpdateOne) Where(ps ...predicate.GtkPosition) *GtkPositionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GtkPositionUpdateOne) Select(field string, fields ...string) *GtkPositionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GtkPosition entity.
func (_u *GtkPositionUpdateOne) Save(ctx context.Context) (*GtkPosition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GtkPositionUpdateOne) SaveX(ctx context.Context) *GtkPosition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GtkPositionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GtkPositionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GtkPositionUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := gtkposition.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GtkPosition.title": %w`, err)}
		}
	}
	if _u.mutation.GtkCleared() && len(_u.mutation.GtkIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GtkPosition.gtk"`)
	}
	if _u.mutation.DepartmentCleared() && len(_u.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GtkPosition.department"`)
	}
	return nil
}

func (_u *GtkPositionUpdateOne) sqlSave(ctx context.Context) (_node *GtkPosition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gtkposition.Table, gtkposition.Columns, sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GtkPosition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gtkposition.FieldID)
		for _, f := range fields {
			if !gtkposition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gtkposition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(gtkposition.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(gtkposition.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(gtkposition.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(gtkposition.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(gtkposition.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.GtkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.GtkTable,
			Columns: []string{gtkposition.GtkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GtkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.GtkTable,
			Columns: []string{gtkposition.GtkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gtk.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.DepartmentTable,
			Columns: []string{gtkposition.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gtkposition.DepartmentTable,
			Columns: []string{gtkposition.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.GtkPosition
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.GtkPosition
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &GtkPosition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gtkposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
