// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/department"
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GtkPositionQuery is the builder for querying GtkPosition entities.
type GtkPositionQuery struct {
	config
	ctx            *QueryContext
	order          []gtkposition.OrderOption
	inters         []Interceptor
	predicates     []predicate.GtkPosition
	withGtk        *GtkQuery
	withDepartment *DepartmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GtkPositionQuery builder.
func (_q *GtkPositionQuery) Where(ps ...predicate.GtkPosition) *GtkPositionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GtkPositionQuery) Limit(limit int) *GtkPositionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GtkPositionQuery) Offset(offset int) *GtkPositionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GtkPositionQuery) Unique(unique bool) *GtkPositionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GtkPositionQuery) Order(o ...gtkposition.OrderOption) *GtkPositionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGtk chains the current query on the "gtk" edge.
func (_q *GtkPositionQuery) QueryGtk() *GtkQuery {
	query := (&GtkClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gtkposition.Table, gtkposition.FieldID, selector),
			sqlgraph.To(gtk.Table, gtk.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gtkposition.GtkTable, gtkposition.GtkColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.Gtk
		step.Edge.Schema = schemaConfig.GtkPosition
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDepartment chains the current query on the "department" edge.
func (_q *GtkPositionQuery) QueryDepartment() *DepartmentQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gtkposition.Table, gtkposition.FieldID, selector),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gtkposition.DepartmentTable, gtkposition.DepartmentColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.Department
		step.Edge.Schema = schemaConfig.GtkPosition
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GtkPosition entity from the query.
// Returns a *NotFoundError when no GtkPosition was found.
func (_q *GtkPositionQuery) First(ctx context.Context) (*GtkPosition, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gtkposition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GtkPositionQuery) FirstX(ctx context.Context) *GtkPosition {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GtkPosition ID from the query.
// Returns a *NotFoundError when no GtkPosition ID was found.
func (_q *GtkPositionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gtkposition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GtkPositionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GtkPosition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GtkPosition entity is found.
// Returns a *NotFoundError when no GtkPosition entities are found.
func (_q *GtkPositionQuery) Only(ctx context.Context) (*GtkPosition, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gtkposition.Label}
	default:
		return nil, &NotSingularError{gtkposition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GtkPositionQuery) OnlyX(ctx context.Context) *GtkPosition {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GtkPosition ID in the query.
// Returns a *NotSingularError when more than one GtkPosition ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GtkPositionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gtkposition.Label}
	default:
		err = &NotSingularError{gtkposition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GtkPositionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GtkPositions.
func (_q *GtkPositionQuery) All(ctx context.Context) ([]*GtkPosition, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GtkPosition, *GtkPositionQuery]()
	return withInterceptors[[]*GtkPosition](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GtkPositionQuery) AllX(ctx context.Context) []*GtkPosition {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GtkPosition IDs.
func (_q *GtkPositionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(gtkposition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GtkPositionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GtkPositionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GtkPositionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GtkPositionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GtkPositionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GtkPositionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GtkPositionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GtkPositionQuery) Clone() *GtkPositionQuery {
	if _q == nil {
		return nil
	}
	return &GtkPositionQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]gtkposition.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.GtkPosition{}, _q.predicates...),
		withGtk:        _q.withGtk.Clone(),
		withDepartment: _q.withDepartment.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGtk tells the query-builder to eager-load the nodes that are connected to
// the "gtk" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GtkPositionQuery) WithGtk(opts ...func(*GtkQuery)) *GtkPositionQuery {
	query := (&GtkClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGtk = query
	return _q
}

// WithDepartment tells the query-builder to eager-load the nodes that are connected to
// the "department" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GtkPositionQuery) WithDepartment(opts ...func(*DepartmentQuery)) *GtkPositionQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDepartment = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GtkID uuid.UUID `json:"gtk_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GtkPosition.Query().
//		GroupBy(gtkposition.FieldGtkID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GtkPositionQuery) GroupBy(field string, fields ...string) *GtkPositionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GtkPositionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = gtkposition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GtkID uuid.UUID `json:"gtk_id,omitempty"`
//	}
//
//	client.GtkPosition.Query().
//		Select(gtkposition.FieldGtkID).
//		Scan(ctx, &v)
func (_q *GtkPositionQuery) Select(fields ...string) *GtkPositionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GtkPositionSelect{GtkPositionQuery: _q}
	sbuild.label = gtkposition.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GtkPositionSelect configured with the given aggregations.
func (_q *GtkPositionQuery) Aggregate(fns ...AggregateFunc) *GtkPositionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GtkPositionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !gtkposition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GtkPositionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GtkPosition, error) {
	var (
		nodes       = []*GtkPosition{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withGtk != nil,
			_q.withDepartment != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GtkPosition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GtkPosition{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.GtkPosition
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGtk; query != nil {
		if err := _q.loadGtk(ctx, query, nodes, nil,
			func(n *GtkPosition, e *Gtk) { n.Edges.Gtk = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDepartment; query != nil {
		if err := _q.loadDepartment(ctx, query, nodes, nil,
			func(n *GtkPosition, e *Department) { n.Edges.Department = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GtkPositionQuery) loadGtk(ctx context.Context, query *GtkQuery, nodes []*GtkPosition, init func(*GtkPosition), assign func(*GtkPosition, *Gtk)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GtkPosition)
	for i := range nodes {
		fk := nodes[i].GtkID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(gtk.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "gtk_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GtkPositionQuery) loadDepartment(ctx context.Context, query *DepartmentQuery, nodes []*GtkPosition, init func(*GtkPosition), assign func(*GtkPosition, *Department)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GtkPosition)
	for i := range nodes {
		fk := nodes[i].DepartmentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(department.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "department_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GtkPositionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.GtkPosition
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GtkPositionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gtkposition.Table, gtkposition.Columns, sqlgraph.NewFieldSpec(gtkposition.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gtkposition.FieldID)
		for i := range fields {
			if fields[i] != gtkposition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGtk != nil {
			_spec.Node.AddColumnOnce(gtkposition.FieldGtkID)
		}
		if _q.withDepartment != nil {
			_spec.Node.AddColumnOnce(gtkposition.FieldDepartmentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GtkPositionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(gtkposition.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = gtkposition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.GtkPosition)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GtkPositionGroupBy is the group-by builder for GtkPosition entities.
type GtkPositionGroupBy struct {
	selector
	build *GtkPositionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GtkPositionGroupBy) Aggregate(fns ...AggregateFunc) *GtkPositionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GtkPositionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GtkPositionQuery, *GtkPositionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GtkPositionGroupBy) sqlScan(ctx context.Context, root *GtkPositionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GtkPositionSelect is the builder for selecting fields of GtkPosition entities.
type GtkPositionSelect struct {
	*GtkPositionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GtkPositionSelect) Aggregate(fns ...AggregateFunc) *GtkPositionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GtkPositionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GtkPositionQuery, *GtkPositionSelect](ctx, _s.GtkPositionQuery, _s, _s.inters, v)
}

func (_s *GtkPositionSelect) sqlScan(ctx context.Context, root *GtkPositionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
