// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/department"
	"backend/internal/ent/gtk"
	"backend/internal/ent/gtkposition"
	"backend/internal/ent/schema"
	"backend/internal/ent/tenant"
	"backend/internal/ent/tenantuser"
	"backend/internal/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescName is the schema descriptor for name field.
	departmentDescName := departmentFields[1].Descriptor()
	// department.NameValidator is a validator for the "name" field. It is called by the builders before save.
	department.NameValidator = departmentDescName.Validators[0].(func(string) error)
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentFields[0].Descriptor()
	// department.DefaultID holds the default value on creation for the id field.
	department.DefaultID = departmentDescID.Default.(func() uuid.UUID)
	gtkFields := schema.Gtk{}.Fields()
	_ = gtkFields
	// gtkDescNik is the schema descriptor for nik field.
	gtkDescNik := gtkFields[2].Descriptor()
	// gtk.NikValidator is a validator for the "nik" field. It is called by the builders before save.
	gtk.NikValidator = func() func(string) error {
		validators := gtkDescNik.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(nik string) error {
			for _, fn := range fns {
				if err := fn(nik); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gtkDescNuptk is the schema descriptor for nuptk field.
	gtkDescNuptk := gtkFields[3].Descriptor()
	// gtk.NuptkValidator is a validator for the "nuptk" field. It is called by the builders before save.
	gtk.NuptkValidator = gtkDescNuptk.Validators[0].(func(string) error)
	// gtkDescFullName is the schema descriptor for full_name field.
	gtkDescFullName := gtkFields[4].Descriptor()
	// gtk.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	gtk.FullNameValidator = gtkDescFullName.Validators[0].(func(string) error)
	// gtkDescGender is the schema descriptor for gender field.
	gtkDescGender := gtkFields[5].Descriptor()
	// gtk.GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	gtk.GenderValidator = gtkDescGender.Validators[0].(func(string) error)
	// gtkDescBirthPlace is the schema descriptor for birth_place field.
	gtkDescBirthPlace := gtkFields[6].Descriptor()
	// gtk.BirthPlaceValidator is a validator for the "birth_place" field. It is called by the builders before save.
	gtk.BirthPlaceValidator = gtkDescBirthPlace.Validators[0].(func(string) error)
	// gtkDescEmploymentStatus is the schema descriptor for employment_status field.
	gtkDescEmploymentStatus := gtkFields[8].Descriptor()
	// gtk.EmploymentStatusValidator is a validator for the "employment_status" field. It is called by the builders before save.
	gtk.EmploymentStatusValidator = gtkDescEmploymentStatus.Validators[0].(func(string) error)
	// gtkDescIsActive is the schema descriptor for is_active field.
	gtkDescIsActive := gtkFields[9].Descriptor()
	// gtk.DefaultIsActive holds the default value on creation for the is_active field.
	gtk.DefaultIsActive = gtkDescIsActive.Default.(bool)
	// gtkDescCreatedAt is the schema descriptor for created_at field.
	gtkDescCreatedAt := gtkFields[11].Descriptor()
	// gtk.DefaultCreatedAt holds the default value on creation for the created_at field.
	gtk.DefaultCreatedAt = gtkDescCreatedAt.Default.(func() time.Time)
	// gtkDescUpdatedAt is the schema descriptor for updated_at field.
	gtkDescUpdatedAt := gtkFields[12].Descriptor()
	// gtk.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gtk.DefaultUpdatedAt = gtkDescUpdatedAt.Default.(func() time.Time)
	// gtk.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gtk.UpdateDefaultUpdatedAt = gtkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// gtkDescID is the schema descriptor for id field.
	gtkDescID := gtkFields[0].Descriptor()
	// gtk.DefaultID holds the default value on creation for the id field.
	gtk.DefaultID = gtkDescID.Default.(func() uuid.UUID)
	gtkpositionFields := schema.GtkPosition{}.Fields()
	_ = gtkpositionFields
	// gtkpositionDescTitle is the schema descriptor for title field.
	gtkpositionDescTitle := gtkpositionFields[3].Descriptor()
	// gtkposition.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	gtkposition.TitleValidator = gtkpositionDescTitle.Validators[0].(func(string) error)
	// gtkpositionDescIsPrimary is the schema descriptor for is_primary field.
	gtkpositionDescIsPrimary := gtkpositionFields[4].Descriptor()
	// gtkposition.DefaultIsPrimary holds the default value on creation for the is_primary field.
	gtkposition.DefaultIsPrimary = gtkpositionDescIsPrimary.Default.(bool)
	// gtkpositionDescID is the schema descriptor for id field.
	gtkpositionDescID := gtkpositionFields[0].Descriptor()
	// gtkposition.DefaultID holds the default value on creation for the id field.
	gtkposition.DefaultID = gtkpositionDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSchemaName is the schema descriptor for schema_name field.
	tenantDescSchemaName := tenantFields[2].Descriptor()
	// tenant.SchemaNameValidator is a validator for the "schema_name" field. It is called by the builders before save.
	tenant.SchemaNameValidator = tenantDescSchemaName.Validators[0].(func(string) error)
	// tenantDescIsActive is the schema descriptor for is_active field.
	tenantDescIsActive := tenantFields[4].Descriptor()
	// tenant.DefaultIsActive holds the default value on creation for the is_active field.
	tenant.DefaultIsActive = tenantDescIsActive.Default.(bool)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[6].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantuserFields := schema.TenantUser{}.Fields()
	_ = tenantuserFields
	// tenantuserDescRole is the schema descriptor for role field.
	tenantuserDescRole := tenantuserFields[3].Descriptor()
	// tenantuser.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	tenantuser.RoleValidator = tenantuserDescRole.Validators[0].(func(string) error)
	// tenantuserDescCreatedAt is the schema descriptor for created_at field.
	tenantuserDescCreatedAt := tenantuserFields[4].Descriptor()
	// tenantuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantuser.DefaultCreatedAt = tenantuserDescCreatedAt.Default.(func() time.Time)
	// tenantuserDescID is the schema descriptor for id field.
	tenantuserDescID := tenantuserFields[0].Descriptor()
	// tenantuser.DefaultID holds the default value on creation for the id field.
	tenantuser.DefaultID = tenantuserDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescFullName is the schema descriptor for full_name field.
	userDescFullName := userFields[3].Descriptor()
	// user.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	user.FullNameValidator = userDescFullName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
