// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"backend/internal/ent/tenant"
	"backend/internal/ent/tenantuser"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSchemaName sets the "schema_name" field.
func (_u *TenantUpdate) SetSchemaName(v string) *TenantUpdate {
	_u.mutation.SetSchemaName(v)
	return _u
}

// SetNillableSchemaName sets the "schema_name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSchemaName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSchemaName(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdate) SetDomain(v string) *TenantUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdate) ClearDomain() *TenantUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TenantUpdate) SetIsActive(v bool) *TenantUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableIsActive(v *bool) *TenantUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTenantUserIDs adds the "tenant_users" edge to the TenantUser entity by IDs.
func (_u *TenantUpdate) AddTenantUserIDs(ids ...uuid.UUID) *TenantUpdate {
	_u.mutation.AddTenantUserIDs(ids...)
	return _u
}

// AddTenantUsers adds the "tenant_users" edges to the TenantUser entity.
func (_u *TenantUpdate) AddTenantUsers(v ...*TenantUser) *TenantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTenantUserIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearTenantUsers clears all "tenant_users" edges to the TenantUser entity.
func (_u *TenantUpdate) ClearTenantUsers() *TenantUpdate {
	_u.mutation.ClearTenantUsers()
	return _u
}

// RemoveTenantUserIDs removes the "tenant_users" edge to TenantUser entities by IDs.
func (_u *TenantUpdate) RemoveTenantUserIDs(ids ...uuid.UUID) *TenantUpdate {
	_u.mutation.RemoveTenantUserIDs(ids...)
	return _u
}

// RemoveTenantUsers removes "tenant_users" edges to TenantUser entities.
func (_u *TenantUpdate) RemoveTenantUsers(v ...*TenantUser) *TenantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTenantUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SchemaName(); ok {
		if err := tenant.SchemaNameValidator(v); err != nil {
			return &ValidationError{Name: "schema_name", err: fmt.Errorf(`ent: validator failed for field "Tenant.schema_name": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaName(); ok {
		_spec.SetField(tenant.FieldSchemaName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(tenant.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TenantUsersTable,
			Columns: []string{tenant.TenantUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTenantUsersIDs(); len(nodes) > 0 && !_u.mutation.TenantUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TenantUsersTable,
			Columns: []string{tenant.TenantUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TenantUsersTable,
			Columns: []string{tenant.TenantUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Tenant
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSchemaName sets the "schema_name" field.
func (_u *TenantUpdateOne) SetSchemaName(v string) *TenantUpdateOne {
	_u.mutation.SetSchemaName(v)
	return _u
}

// SetNillableSchemaName sets the "schema_name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSchemaName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSchemaName(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdateOne) SetDomain(v string) *TenantUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdateOne) ClearDomain() *TenantUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TenantUpdateOne) SetIsActive(v bool) *TenantUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableIsActive(v *bool) *TenantUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTenantUserIDs adds the "tenant_users" edge to the TenantUser entity by IDs.
func (_u *TenantUpdateOne) AddTenantUserIDs(ids ...uuid.UUID) *TenantUpdateOne {
	_u.mutation.AddTenantUserIDs(ids...)
	return _u
}

// AddTenantUsers adds the "tenant_users" edges to the TenantUser entity.
func (_u *TenantUpdateOne) AddTenantUsers(v ...*TenantUser) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTenantUserIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearTenantUsers clears all "tenant_users" edges to the TenantUser entity.
func (_u *TenantUpdateOne) ClearTenantUsers() *TenantUpdateOne {
	_u.mutation.ClearTenantUsers()
	return _u
}

// RemoveTenantUserIDs removes the "tenant_users" edge to TenantUser entities by IDs.
func (_u *TenantUpdateOne) RemoveTenantUserIDs(ids ...uuid.UUID) *TenantUpdateOne {
	_u.mutation.RemoveTenantUserIDs(ids...)
	return _u
}

// RemoveTenantUsers removes "tenant_users" edges to TenantUser entities.
func (_u *TenantUpdateOne) RemoveTenantUsers(v ...*TenantUser) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTenantUserIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SchemaName(); ok {
		if err := tenant.SchemaNameValidator(v); err != nil {
			return &ValidationError{Name: "schema_name", err: fmt.Errorf(`ent: validator failed for field "Tenant.schema_name": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaName(); ok {
		_spec.SetField(tenant.FieldSchemaName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(tenant.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TenantUsersTable,
			Columns: []string{tenant.TenantUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTenantUsersIDs(); len(nodes) > 0 && !_u.mutation.TenantUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TenantUsersTable,
			Columns: []string{tenant.TenantUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TenantUsersTable,
			Columns: []string{tenant.TenantUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Tenant
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
