// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/internal"
	"backend/internal/ent/predicate"
	"backend/internal/ent/tenant"
	"backend/internal/ent/tenantuser"
	"backend/internal/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TenantUserUpdate is the builder for updating TenantUser entities.
type TenantUserUpdate struct {
	config
	hooks    []Hook
	mutation *TenantUserMutation
}

// Where appends a list predicates to the TenantUserUpdate builder.
func (_u *TenantUserUpdate) Where(ps ...predicate.TenantUser) *TenantUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantUserUpdate) SetTenantID(v uuid.UUID) *TenantUserUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantUserUpdate) SetNillableTenantID(v *uuid.UUID) *TenantUserUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantUserUpdate) SetUserID(v uuid.UUID) *TenantUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantUserUpdate) SetNillableUserID(v *uuid.UUID) *TenantUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TenantUserUpdate) SetRole(v string) *TenantUserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TenantUserUpdate) SetNillableRole(v *string) *TenantUserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantUserUpdate) SetTenant(v *Tenant) *TenantUserUpdate {
	return _u.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantUserUpdate) SetUser(v *User) *TenantUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TenantUserMutation object of the builder.
func (_u *TenantUserUpdate) Mutation() *TenantUserMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantUserUpdate) ClearTenant() *TenantUserUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantUserUpdate) ClearUser() *TenantUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUserUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := tenantuser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TenantUser.role": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.tenant"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.user"`)
	}
	return nil
}

func (_u *TenantUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantuser.Table, tenantuser.Columns, sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(tenantuser.FieldRole, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.TenantUser
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUserUpdateOne is the builder for updating a single TenantUser entity.
type TenantUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantUserMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantUserUpdateOne) SetTenantID(v uuid.UUID) *TenantUserUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantUserUpdateOne) SetNillableTenantID(v *uuid.UUID) *TenantUserUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantUserUpdateOne) SetUserID(v uuid.UUID) *TenantUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantUserUpdateOne) SetNillableUserID(v *uuid.UUID) *TenantUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TenantUserUpdateOne) SetRole(v string) *TenantUserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TenantUserUpdateOne) SetNillableRole(v *string) *TenantUserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantUserUpdateOne) SetTenant(v *Tenant) *TenantUserUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantUserUpdateOne) SetUser(v *User) *TenantUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TenantUserMutation object of the builder.
func (_u *TenantUserUpdateOne) Mutation() *TenantUserMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantUserUpdateOne) ClearTenant() *TenantUserUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantUserUpdateOne) ClearUser() *TenantUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TenantUserUpdate builder.
func (_u *TenantUserUpdateOne) Where(ps ...predicate.TenantUser) *TenantUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUserUpdateOne) Select(field string, fields ...string) *TenantUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantUser entity.
func (_u *TenantUserUpdateOne) Save(ctx context.Context) (*TenantUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUserUpdateOne) SaveX(ctx context.Context) *TenantUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUserUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := tenantuser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TenantUser.role": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.tenant"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.user"`)
	}
	return nil
}

func (_u *TenantUserUpdateOne) sqlSave(ctx context.Context) (_node *TenantUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantuser.Table, tenantuser.Columns, sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantuser.FieldID)
		for _, f := range fields {
			if !tenantuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(tenantuser.FieldRole, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.TenantUser
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &TenantUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
