// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Gtk is the predicate function for gtk builders.
type Gtk func(*sql.Selector)

// GtkPosition is the predicate function for gtkposition builders.
type GtkPosition func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantUser is the predicate function for tenantuser builders.
type TenantUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
